### ISSUE TITLE
一顿操作猛如虎，一看没有数据库

### ISSUE THREAD

**Issue by PitakaDrive** [gedongdong/laravel_rbac_permission#22]
数据库都没有唉。不知道是不是故意省去了数据库，migrate中也不存在。那么多截图，浪费

**Comment by gedongdong** [comment]
https://github.com/gedongdong/laravel_rbac_permission/blob/master/rbac.sql
这个就是数据库啊

**Comment by gedongdong** [comment]
> 数据库都没有唉。不知道是不是故意省去了数据库，migrate中也不存在。那么多截图，浪费

https://github.com/gedongdong/laravel_rbac_permission/blob/master/rbac.sql
